# _config.yml
title: "付亚鹏"
author: "付亚鹏 (Ya-Peng Fu)"
description: "个人网页"
# 您的邮箱，将用于JS保护，不会直接暴露在源码中
email: "fuyapeng@ucass.edu.cn"
github_username: "fyapeng" # 替换为您的GitHub用户名

# Jekyll Plugins
plugins:
  - jekyll-minifier
  - jekyll-seo-tag

# Jekyll-Minifier Configuration
# This will automatically run when building on GitHub Pages
jekyll-minifier:
  exclude: ['CNAME', 'LICENSE']
  uglifier_args:
    harmony: true

# 重要的网站URL配置
url: "https://fyapeng.com" # 确保是 https 和您的自定义域名
baseurl: "" # 必须是空字符串，不是 "/"

# Default configurations for pages
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default" # Use the default layout
  -
    scope:
      path: "en" # For all files inside the /en/ directory
    values:
      lang: "en"
      # Example of setting a permalink structure for English pages
      # permalink: /en/:basename/
  -
    scope:
      path: ""
      type: "pages"
    values:
      lang: "zh" # Default language for top-level pages is Chinese
